### PR TITLE
New screenshots, mention RainViewer, typo fix.

### PR DESCRIPTION
**Pull request by 0-5-0**
New screenshots to show rain section in Current forecast, new preferences and weather map transparency. Added mention of RainViewer to readme and android description. Fixed typo in preference text.

### CODE REVIEW

**Comment by farfromrefug** [comment]
@0-5-0 btw i might be wrong but i feel like i have to thank you too for the review on the play store ?

**Comment by 0-5-0** [comment]
Haha, I did add one this afternoon :)

**Comment by farfromrefug** [comment]
@0-5-0 thank you ! felt like it was you ;)
dont know if you are French by if one day you go by Grenoble in France ping me and I ll happily buy you a beer!

**Comment by 0-5-0** [comment]
Hehe, french canadian, a bit far but I'll reach out if I'm ever heading that way :)

**Pull request merged**
