### PR TITLE
Russian translation

### PR DESCRIPTION
**Pull request by Dimoon12**
Added 2 awesome languages!

### CODE REVIEW

**Comment by Dimoon12** [comment]
yaay enjoy :3

**Comment by farfromrefug** [comment]
@Dimoon12 awesome thank you. Will make a release. What is strange EN ?

**Comment by Dimoon12** [comment]
@farfromrefug a little bit of wierd languages, you can remove it, but i think that will be fun

**Comment by farfromrefug** [comment]
@Dimoon12 ok will take a look ;)

**Pull request closed without merging**
