### PR TITLE
Add Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by Yogotami**

### CODE REVIEW

**Comment by farfromrefug** [comment]
@Yogotami awesome thanks!

**Comment by Yogotami** [comment]
Wanted to ask you about the cardinal points. Those are not the standard names, are they? I saw in the code that it automatically gets the cardinal points and writes its abbreviation. Is the purpose of this .json just to change what the code writes? If it is, then we'll need to fix all the cardinal points from the translations.

ps: I'm not very savvy, just very interested.

**Comment by farfromrefug** [comment]
@Yogotami i think they are standard for english, arent they? And yes the app use the abbreviation to show the moon position

**Comment by Yogotami** [comment]
According to this, some are different from the code (which cause a bit of confusion for me):
image

**Comment by farfromrefug** [comment]
Ok i LL check thanks

**Pull request merged**
